<a href="https://colab.research.google.com/github/willismax/MediaSystem-Python-Course/blob/main/01.Intro-Python/NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 基礎教學

### 課程大綱
1. 介紹與安裝
2. 基本操作
3. 索引與切片
4. 數組操作
5. 數學函數
6. 統計函數
7. 形狀操作
8. 高級操作與應用
9. 計算運用

#### 1. 介紹與安裝

- NumPy（Numerical Python）是一個用於科學計算的開源 Python 庫。它由 Travis Oliphant 在2005年建立，目的是要整合當時已存在的數學庫 Numeric 和 Numarray，並提供更強大、更高效的數組操作能力。
- NumPy是Python的一個工具，可以幫助我們進行數學計算。首先，我們需要安裝並導入它。

In [ ]:
# 安裝 NumPy， Colab 已經有裝
!pip install -q numpy

In [2]:
# 導入 NumPy
import numpy as np

#### 2. 基本操作
**目標**: 學習如何建立和操作數組。
**內容**: 數組是一種有序排列的數字。這裡我們會學習如何創建和使用它們。

In [ ]:
import numpy as np

# 建立一個一維數組
array_1d = np.array([1, 2, 3, 4, 5])
array_1d.shape

(5,)

In [ ]:
# 建立一個二維數組
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d.shape

(2, 3)

In [ ]:
# 基本操作
array_1d + 10

array([11, 12, 13, 14, 15])

In [ ]:
array_2d * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

#### 3. 索引與切片
**目標**: 學習如何找到和取出數組中的部分數字。
**內容**: 我們可以使用索引來找到數組中的特定數字，使用切片來取出一部分數字。

In [ ]:
import numpy as np

# 一維數組索引
array_1d = np.array([1, 2, 3, 4, 5])
array_1d[0]  # 取得第一個數字

1

In [ ]:
# 二維數組索引
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d[1, 2]  # 取得第二排第三個數字

6

In [ ]:
# 切片操作
array_1d[1:4]  # 取得第二到第四個數字

array([2, 3, 4])

In [ ]:
array_2d[:, 1:3]  # 取得所有行的第二到第三列

array([[2, 3],
       [5, 6]])

#### 4. 數組操作
可以將兩個數組合併成一個，或將一個數組分成多個，還可以複製數組。

- 合併數組


In [ ]:
import numpy as np

array_1d = np.array([1, 2, 3])

# 合併數組
array_v = np.vstack((array_1d, array_1d))  # 垂直合併
print(array_v)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
array_h = np.hstack((array_1d, array_1d))  # 水平合併
print(array_h)

[1 2 3 4 5 1 2 3 4 5]


In [ ]:
# 分割數組
split_array = np.split(array_1d, 5)  # 分成五個部分
print(split_array)

[array([1]), array([2]), array([3]), array([4]), array([5])]


In [ ]:
# 複製數組
array_copy = np.copy(array_1d)  # 複製
print(array_copy)

[1 2 3 4 5]


#### 5. 數學函數
可以對數組中的數字進行加減乘除等操作。

In [4]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])

# 加減乘除
print(np.add(array_1d, 5))  # 每個數字加5
print(np.subtract(array_1d, 2))  # 每個數字減2
print(np.multiply(array_1d, 3))  # 每個數字乘3
print(np.divide(array_1d, 2))  # 每個數字除以2



[ 6  7  8  9 10]
[-1  0  1  2  3]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [ ]:
# 指數與對數
print(np.exp(array_1d))  # 每個數字的指數值
print(np.log(array_1d))  # 每個數字的對數值

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
# 三角函數
print(np.sin(array_1d))  # 每個數字的正弦值
print(np.cos(array_1d))  # 每個數字的餘弦值

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


#### 6. 統計函數
**目標**: 學習常用的統計操作。
**內容**: 我們可以找到數組中的最大值、最小值、平均值等。

In [5]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])

# 統計函數
print(np.min(array_1d))  # 最小值
print(np.max(array_1d))  # 最大值
print(np.mean(array_1d))  # 平均值
print(np.std(array_1d))  # 標準差
print(np.var(array_1d))  # 變異數(方差)

1
5
3.0
1.4142135623730951
2.0


#### 7. 形狀操作
**目標**: 學習如何改變數組的形狀。
**內容**: 我們可以改變數組的形狀，讓它變成不同的結構。

In [6]:
import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 重塑數組
array_reshaped = np.reshape(array_2d, (3, 2))  # 改變形狀為3行2列
print(array_reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# 轉置數組
array_transposed = np.transpose(array_2d)  # 行列互換
print(array_transposed)

[[1 4]
 [2 5]
 [3 6]]


#### 8. 高級操作與應用
**目標**: 了解NumPy在高級操作中的應用。
**內容**: 我們可以將數組存成檔案，做線性代數計算，生成隨機數。

In [7]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])

# 序列化與反序列化
np.save('array.npy', array_1d)  # 保存到檔案
loaded_array = np.load('array.npy')  # 從檔案讀取
print(loaded_array)

[1 2 3 4 5]


In [8]:
# 線性代數
matrix = np.array([[1, 2], [3, 4]])
inverse_matrix = np.linalg.inv(matrix)  # 求逆矩陣
print(inverse_matrix)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [9]:
# 隨機數生成
random_array = np.random.random((2, 3))  # 生成2行3列的隨機數組
print(random_array)

[[0.17647656 0.48805574 0.17940235]
 [0.99700418 0.05390199 0.4827274 ]]


#### 9. 計算運用

##### 向量化 (Vectorization)

- 向量化是指使用數組運算來取代明確的循環操作。這種方法能夠使數學運算在數組上更快、更高效。NumPy 提供的許多函數和操作都已經向量化，這意味著它們能夠直接對整個數組進行操作，而不需要寫循環。

- 假設我們有兩個數組，並想對它們的每個元素進行相加。如果使用傳統的循環，我們可能會這樣做：

這樣的操作在 NumPy 中不僅更簡潔，還能充分利用底層的 C 和 Fortran 優化，提高計算效率。


In [10]:
# 傳統循環方法
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])
result = np.zeros(4)

for i in range(len(array1)):
    result[i] = array1[i] + array2[i]

print(result)

[ 6.  8. 10. 12.]


使用向量化，我們可以簡化成：

In [11]:
# 向量化方法
result = array1 + array2
print(result)

[ 6  8 10 12]


##### 廣播 (Broadcasting)

廣播是指在數組運算中，NumPy 允許不同形狀的數組進行操作，並自動將較小的數組擴展為與較大數組相同的形狀，從而使運算順利進行。廣播的核心思想是擴展數組，使它們具有兼容的形狀，這樣就可以進行元素級別的操作。

##### 廣播的例子

假設我們有一個數組和一個標量，想要對數組中的每個元素加上這個量。通常我們會這樣做：



In [12]:
# 傳統循環方法
array = np.array([1, 2, 3, 4])
scalar = 10
result = np.zeros(4)

for i in range(len(array)):
    result[i] = array[i] + scalar

print(result)

[11. 12. 13. 14.]


使用廣播，我們可以這樣做：


In [13]:
# 廣播方法
result = array + scalar
print(result)

[11 12 13 14]



#### 不同形狀數組的廣播

- 廣播也可以應用於不同形狀的數組。例如，一個形狀為 (4, 1) 的數組和一個形狀為 (1, 3) 的數組相加：
- 這裡，`array1` 會被擴展為 (4, 3) 的形狀，而 `array2` 也會被擴展為 (4, 3) 的形狀，然後再進行加法運算。結果如下：

In [14]:
array1 = np.array([[1], [2], [3], [4]])
array2 = np.array([[10, 20, 30]])

result = array1 + array2
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]


In [17]:
import numpy as np

# 定義曲線調整的中心值，即期望調整後成績的平均值
CURVE_CENTER = 80

# 初始化成績數組，包含多個學生的成績
grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])

def curve(grades):
    # 計算當前成績的平均值
    average = grades.mean()

    # 計算調整量，即中心值與當前平均值之間的差
    change = CURVE_CENTER - average

    # 將調整量加到每個成績上，得到新的成績
    new_grades = grades + change

    # 使用 np.clip 函數限制新的成績，確保不低於原始成績且不超過100分
    return np.clip(new_grades, grades, 100)

# 調整成績，並將結果存儲在 curved_grades 中
curved_grades = curve(grades)

# 輸出調整後的成績
print(curved_grades)


[ 91.25  54.25  83.25 100.    70.25 100.    93.25  31.25]


### 參考來源
1. NumPy 官方文件：https://numpy.org/doc/stable/
2. Python Documentation：https://docs.python.org/3/
3. [W3Schools NumPy Tutorial](https://www.w3schools.com/python/numpy_intro.asp)
4. [NumPy Tutorial (Real Python)](https://realpython.com/numpy-tutorial/)
5. ChatGPT